/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8v64DgROmxm
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Home() {
  return (
    <Card className="w-full max-w-md">
      <CardHeader className="flex items-center justify-between">
        <CardTitle className="text-2xl font-bold">Daily Habits</CardTitle>
        <Button variant="outline" size="icon">
          <PlusIcon className="h-5 w-5" />
          <span className="sr-only">Add Habit</span>
        </Button>
      </CardHeader>
      <CardContent>
        <div className="grid gap-4">
          <div className="flex items-center justify-between bg-primary/10 rounded-md p-4">
            <div className="flex items-center gap-3">
              <div className="bg-primary/20 rounded-md flex items-center justify-center aspect-square w-10">
                <DumbbellIcon className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="font-medium">Exercise</div>
                <div className="text-sm text-muted-foreground">30 minutes per day</div>
              </div>
            </div>
            <CheckIcon className="h-6 w-6 text-primary" />
          </div>
          <div className="flex items-center justify-between bg-primary/10 rounded-md p-4">
            <div className="flex items-center gap-3">
              <div className="bg-primary/20 rounded-md flex items-center justify-center aspect-square w-10">
                <BookIcon className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="font-medium">Read</div>
                <div className="text-sm text-muted-foreground">20 pages per day</div>
              </div>
            </div>
            <CheckIcon className="h-6 w-6 text-primary" />
          </div>
          <div className="flex items-center justify-between bg-primary/10 rounded-md p-4">
            <div className="flex items-center gap-3">
              <div className="bg-primary/20 rounded-md flex items-center justify-center aspect-square w-10">
                <DropletIcon className="h-5 w-5 text-primary" />
              </div>
              <div>
                <div className="font-medium">Hydrate</div>
                <div className="text-sm text-muted-foreground">8 glasses per day</div>
              </div>
            </div>
            <CheckIcon className="h-6 w-6 text-primary" />
          </div>
        </div>
      </CardContent>
      <CardFooter className="flex flex-col items-start gap-2">
        <div className="flex items-center gap-2 text-primary">
          <CalendarIcon className="h-5 w-5" />
          <div className="text-sm font-medium">Congratulations! You have a 5-day streak.</div>
        </div>
      </CardFooter>
    </Card>
  )
}

function BookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
    </svg>
  )
}


function CalendarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DropletIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22a7 7 0 0 0 7-7c0-2-1-3.9-3-5.5s-3.5-4-4-6.5c-.5 2.5-2 4.9-4 6.5C6 11.1 5 13 5 15a7 7 0 0 0 7 7z" />
    </svg>
  )
}


function DumbbellIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}
